blank_issues_enabled: false
contact_links:
  - name: "Discussions / Q&A"
    url: "https://github.com/xyluo25/Real-Twin/discussions"
    about: "Please ask and answer questions here when possible."
  # - name: "Security vulnerability report"
  #   url: "https://github.com/xyluo25/Real-Twin/security/policy"
  #   about: "Please report security vulnerabilities via the Security tab."